package tokens

import (
	"fmt"
	"path"
	"strings"
)

// Result is compiled tokens.css, the reasons anything in tokens.json was dropped, and the
// accepted tokens in structured form for the site's specimen pages.
type Result struct {
	CSS      string
	Warnings []string

	Themes   []Theme
	Colors   []ColorEntry
	Scales   []ScaleEntry // spacing, radius, shadow, then any other family
	Families []FamilyEntry
	Fonts    []FontEntry
	Styles   []StyleEntry
}

// ColorEntry is an accepted colour token with its value in each theme.
type ColorEntry struct {
	Name   string
	Usage  string
	Values []ThemeValue
}

// ThemeValue is a colour in one theme. Value is resolved to a literal; Alias names the token it
// was an alias of, if any.
type ThemeValue struct {
	Theme string
	Value string
	Alias string
}

// ScaleEntry is an accepted spacing, radius, shadow or other-family token.
type ScaleEntry struct {
	Family string // spacing, radius, shadow, or the key of an other family
	Name   string
	Usage  string
	Value  string
}

// FamilyEntry is an accepted font stack.
type FamilyEntry struct{ Key, Stack string }

// FontEntry is an accepted @font-face source. File is relative to the system folder.
type FontEntry struct{ Family, File, Weight, Style string }

// StyleEntry is an accepted type style.
type StyleEntry struct {
	Group, Name, Family, Size, LineHeight, Weight, LetterSpacing, Usage, Sample string
}

// Options controls how the CSS refers to font files.
type Options struct {
	// FontBase is prefixed to each font file path in @font-face urls. The default (empty) is
	// right when tokens.css sits next to the fonts/ folder.
	FontBase string
}

type valued struct {
	name string            // canonical name, as used by aliases
	vals map[string]string // theme id -> normalised value ("{x}" for an alias)
}

// Compile turns a token document into tokens.css. Values that the platform would not read
// are dropped and reported in Warnings.
func Compile(d *Doc, opt Options) Result {
	var res Result
	w := &res.Warnings
	themes := d.Themes
	if len(themes) == 0 {
		themes = []Theme{{ID: "light", Name: "Light"}}
	}
	if len(themes) > 8 {
		warnf(w, "color.themes: %d themes, only the first 8 are used", len(themes))
		themes = themes[:8]
	}
	for i := range themes {
		themes[i].ID = strings.ToLower(themes[i].ID)
		if !idRe.MatchString(themes[i].ID) {
			warnf(w, "color.themes[%d]: invalid id %q", i, themes[i].ID)
			themes[i].ID = fmt.Sprintf("theme-%d", i+1)
		}
	}
	first := themes[0].ID
	used := map[string]string{} // canonical name -> family, one namespace across families but type

	claim := func(raw, fam string) (string, bool) {
		n, ok := cleanName(raw)
		if !ok {
			warnf(w, "%s %q: invalid name", fam, raw)
			return "", false
		}
		if prev, dup := used[n]; dup {
			warnf(w, "%s %q: duplicate of a %s token, dropped", fam, n, prev)
			return "", false
		}
		used[n] = fam
		return n, true
	}

	usage := map[string]string{}
	for _, fam := range [][]Token{d.Colors, d.Shadows, d.Spacing, d.Radius} {
		for _, t := range fam {
			if n, ok := cleanName(t.Name); ok {
				usage[n] = t.Usage
			}
		}
	}
	for _, o := range d.Others {
		for _, t := range o.Tokens {
			if n, ok := cleanName(t.Name); ok {
				usage[n] = t.Usage
			}
		}
	}

	colors := compileColors(d.Colors, themes, claim, w)
	shadows := compileShadows(d.Shadows, themes, claim, w)
	res.Themes = themes
	res.Colors = colorEntries(colors, themes, usage)

	var b strings.Builder
	b.WriteString("/* Generated by design-export-docs from tokens.json. Do not edit. */\n")

	// First theme.
	b.WriteString(":root, [data-theme=\"" + first + "\"] {\n")
	for _, c := range colors {
		fmt.Fprintf(&b, "  --%s: %s;\n", cssIdent(c.name), emit(c.vals[first]))
	}
	for _, s := range shadows {
		fmt.Fprintf(&b, "  --%s: %s;\n", cssIdent(s.name), s.vals[first])
	}
	b.WriteString("}\n")

	// Further themes: explicit overrides, plus every alias re-declared so it resolves in that theme.
	for _, t := range themes[1:] {
		var lines []string
		for _, c := range colors {
			if v, ok := c.vals[t.ID]; ok {
				lines = append(lines, fmt.Sprintf("  --%s: %s;\n", cssIdent(c.name), emit(v)))
			} else if v := c.vals[first]; aliasRe.MatchString(v) {
				lines = append(lines, fmt.Sprintf("  --%s: %s;\n", cssIdent(c.name), emit(v)))
			}
		}
		for _, s := range shadows {
			if v, ok := s.vals[t.ID]; ok {
				lines = append(lines, fmt.Sprintf("  --%s: %s;\n", cssIdent(s.name), v))
			}
		}
		if len(lines) > 0 {
			b.WriteString("[data-theme=\"" + t.ID + "\"] {\n" + strings.Join(lines, "") + "}\n")
		}
	}

	// Scale families, other families and font stacks on :root.
	var root []string
	addScale := func(fam string, toks []Token, valid func(any) (string, bool)) {
		lines, entries := simpleFamily(fam, toks, valid, claim, w)
		root = append(root, lines...)
		for i := range entries {
			entries[i].Usage = usage[entries[i].Name]
		}
		res.Scales = append(res.Scales, entries...)
	}
	addScale("spacing", d.Spacing, lengthValue)
	addScale("radius", d.Radius, lengthValue)
	for _, sh := range shadows {
		res.Scales = append(res.Scales, ScaleEntry{Family: "shadow", Name: sh.name, Usage: usage[sh.name], Value: sh.vals[first]})
	}
	for _, o := range d.Others {
		addScale(o.Key, o.Tokens, plainValue)
	}
	keys := d.Type.FamilyOrder
	if len(keys) == 0 {
		for k := range d.Type.Families {
			keys = append(keys, k)
		}
	}
	for _, k := range keys {
		stack := d.Type.Families[k]
		if !idRe.MatchString(k) || !familyStack(stack) {
			warnf(w, "type.families %q: invalid, dropped", k)
			continue
		}
		root = append(root, fmt.Sprintf("  --font-%s: %s;\n", cssIdent(strings.ToLower(k)), stack))
		res.Families = append(res.Families, FamilyEntry{Key: strings.ToLower(k), Stack: stack})
	}
	if len(root) > 0 {
		b.WriteString(":root {\n" + strings.Join(root, "") + "}\n")
	}

	for _, f := range d.Type.Fonts {
		css, fe, ok := fontFace(f, opt, w)
		if ok {
			b.WriteString(css)
			res.Fonts = append(res.Fonts, fe)
		}
	}
	for _, g := range d.Type.Groups {
		for _, st := range g.Styles {
			css, se, ok := typeStyle(g, st, d.Type.Families, w)
			if ok {
				b.WriteString(css)
				res.Styles = append(res.Styles, se)
			}
		}
	}
	res.CSS = b.String()
	return res
}

func emit(v string) string {
	if m := aliasRe.FindStringSubmatch(v); m != nil {
		return "var(--" + cssIdent(m[1]) + ")"
	}
	return v
}

func simpleFamily(fam string, toks []Token, valid func(any) (string, bool),
	claim func(string, string) (string, bool), w *[]string) ([]string, []ScaleEntry) {
	var out []string
	var entries []ScaleEntry
	for _, t := range toks {
		n, ok := claim(t.Name, fam)
		if !ok {
			continue
		}
		v, ok := valid(t.Value)
		if !ok {
			warnf(w, "%s %q: invalid value %v, dropped", fam, n, t.Value)
			continue
		}
		out = append(out, fmt.Sprintf("  --%s: %s;\n", cssIdent(n), v))
		entries = append(entries, ScaleEntry{Family: fam, Name: n, Value: v})
	}
	return out, entries
}

func themeValues(v any, themes []Theme, valid func(any) (string, bool)) map[string]string {
	out := map[string]string{}
	first := themes[0].ID
	switch x := v.(type) {
	case map[string]any:
		for _, t := range themes {
			if raw, ok := x[t.ID]; ok {
				if s, ok := valid(raw); ok {
					out[t.ID] = s
				}
			}
		}
	default: // a plain value belongs to the first theme
		if s, ok := valid(v); ok {
			out[first] = s
		}
	}
	return out
}

// borrowFirst gives the first theme the earliest later theme's value when it has none of its own.
func borrowFirst(vals map[string]string, themes []Theme) bool {
	first := themes[0].ID
	if _, ok := vals[first]; ok {
		return true
	}
	for _, t := range themes[1:] {
		if v, ok := vals[t.ID]; ok {
			vals[first] = v
			return true
		}
	}
	return false
}

func compileShadows(toks []Token, themes []Theme, claim func(string, string) (string, bool), w *[]string) []valued {
	var out []valued
	for _, t := range toks {
		n, ok := claim(t.Name, "shadow")
		if !ok {
			continue
		}
		vals := themeValues(t.Value, themes, shadowValue)
		if !borrowFirst(vals, themes) {
			warnf(w, "shadow %q: no valid value, dropped", n)
			continue
		}
		out = append(out, valued{n, vals})
	}
	return out
}

func compileColors(toks []Token, themes []Theme, claim func(string, string) (string, bool), w *[]string) []valued {
	var cs []*valued
	for _, t := range toks {
		n, ok := claim(t.Name, "color")
		if !ok {
			continue
		}
		vals := themeValues(t.Value, themes, colorValue)
		if !borrowFirst(vals, themes) {
			warnf(w, "color %q: no valid value, dropped", n)
			continue
		}
		cs = append(cs, &valued{n, vals})
	}
	// Drop aliases that point nowhere, at themselves, in a cycle or more than 16 deep, until stable.
	for changed := true; changed; {
		changed = false
		byName := map[string]*valued{}
		for _, c := range cs {
			if c != nil {
				byName[c.name] = c
			}
		}
		for i, c := range cs {
			if c == nil {
				continue
			}
			for _, t := range themes {
				v, ok := c.vals[t.ID]
				if !ok || !aliasRe.MatchString(v) {
					continue
				}
				if aliasBad(c, t.ID, themes[0].ID, byName) {
					warnf(w, "color %q (%s): alias %s does not resolve", c.name, t.ID, v)
					delete(c.vals, t.ID)
					changed = true
				}
			}
			if !borrowFirst(c.vals, themes) {
				warnf(w, "color %q: no valid value, dropped", c.name)
				cs[i] = nil
				changed = true
			}
		}
	}
	var out []valued
	for _, c := range cs {
		if c != nil {
			out = append(out, *c)
		}
	}
	return out
}

func aliasBad(c *valued, theme, first string, byName map[string]*valued) bool {
	cur := c
	for depth := 0; ; depth++ {
		v, ok := cur.vals[theme]
		if !ok {
			v = cur.vals[first]
		}
		m := aliasRe.FindStringSubmatch(v)
		if m == nil {
			return false
		}
		if depth >= 16 {
			return true
		}
		target, ok := byName[m[1]]
		if !ok || target == c {
			return true
		}
		cur = target
	}
}

var fontFormats = map[string]string{".woff2": "woff2", ".woff": "woff", ".ttf": "truetype", ".otf": "opentype"}

func fontFace(f Font, opt Options, w *[]string) (string, FontEntry, bool) {
	ext := strings.ToLower(path.Ext(f.File))
	format, ok := fontFormats[ext]
	file := f.File
	if !strings.Contains(file, "/") {
		file = "fonts/" + file
	}
	weight := f.Weight
	if weight == "" {
		weight = "400"
	}
	style := f.Style
	if style == "" {
		style = "normal"
	}
	if !ok || strings.Contains(f.Family, `"`) || f.Family == "" || strings.Contains(file, "..") ||
		strings.ContainsAny(file, `"'()\`) || (style != "normal" && style != "italic" && style != "oblique") {
		warnf(w, "type.fonts %q (%s): invalid, dropped", f.Family, f.File)
		return "", FontEntry{}, false
	}
	if _, ok := fontWeightValue(weight); !ok {
		warnf(w, "type.fonts %q (%s): invalid weight %q, dropped", f.Family, f.File, weight)
		return "", FontEntry{}, false
	}
	css := fmt.Sprintf("@font-face {\n  font-family: %q;\n  src: url(%q) format(%q);\n  font-weight: %s;\n  font-style: %s;\n  font-display: swap;\n}\n",
		f.Family, opt.FontBase+file, format, weight, style)
	return css, FontEntry{Family: f.Family, File: file, Weight: weight, Style: style}, true
}

func typeStyle(g TypeGroup, s TypeStyle, families map[string]string, w *[]string) (string, StyleEntry, bool) {
	n, ok := cleanName(s.Name)
	if !ok {
		warnf(w, "type style %q: invalid name", s.Name)
		return "", StyleEntry{}, false
	}
	size, ok := lengthValue(s.FontSize)
	if !ok {
		warnf(w, "type style %q: invalid fontSize %v, dropped", n, s.FontSize)
		return "", StyleEntry{}, false
	}
	entry := StyleEntry{Group: g.Name, Name: n, Size: size, Usage: s.Usage, Sample: s.Sample}
	var decl []string
	fam := s.Family
	if fam == "" {
		fam = g.Family
	}
	if _, ok := families[fam]; ok && fam != "" {
		decl = append(decl, "font-family: var(--font-"+cssIdent(strings.ToLower(fam))+")")
		entry.Family = families[fam]
	}
	decl = append(decl, "font-size: "+size)
	if v, ok := lineHeightValue(s.LineHeight); ok {
		decl = append(decl, "line-height: "+v)
		entry.LineHeight = v
	}
	if v, ok := fontWeightValue(s.FontWeight); ok {
		decl = append(decl, "font-weight: "+v)
		entry.Weight = v
	}
	if s.FontStyle == "normal" || s.FontStyle == "italic" {
		decl = append(decl, "font-style: "+s.FontStyle)
	}
	if v, ok := lengthValue(s.LetterSpacing); ok {
		decl = append(decl, "letter-spacing: "+v)
		entry.LetterSpacing = v
	}
	if f, ok := s.OpticalSize.(float64); ok {
		decl = append(decl, "font-variation-settings: 'opsz' "+formatNumber(f))
	}
	return "." + cssIdent(n) + " { " + strings.Join(decl, "; ") + "; }\n", entry, true
}

// colorEntries lists accepted colours with each theme's value resolved through aliases.
func colorEntries(colors []valued, themes []Theme, usage map[string]string) []ColorEntry {
	byName := map[string]valued{}
	for _, c := range colors {
		byName[c.name] = c
	}
	first := themes[0].ID
	value := func(c valued, theme string) string {
		if v, ok := c.vals[theme]; ok {
			return v
		}
		return c.vals[first]
	}
	var out []ColorEntry
	for _, c := range colors {
		e := ColorEntry{Name: c.name, Usage: usage[c.name]}
		for _, t := range themes {
			v := value(c, t.ID)
			tv := ThemeValue{Theme: t.ID}
			if m := aliasRe.FindStringSubmatch(v); m != nil {
				tv.Alias = m[1]
			}
			for depth := 0; depth < 16; depth++ { // validated acyclic and shallow in compileColors
				m := aliasRe.FindStringSubmatch(v)
				if m == nil {
					break
				}
				v = value(byName[m[1]], t.ID)
			}
			tv.Value = v
			e.Values = append(e.Values, tv)
		}
		out = append(out, e)
	}
	return out
}
