// Package site writes the static site for one or more exported design systems.
package site

import (
	"embed"
	"errors"
	"fmt"
	"html/template"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/joshmcarthur/design-export-docs/internal/rewrite"
	"github.com/joshmcarthur/design-export-docs/internal/system"
	"github.com/joshmcarthur/design-export-docs/internal/tokens"
)

//go:embed templates/*.html static/*
var assets embed.FS

// marker is written into an output folder so a later build knows it may replace its contents.
const marker = ".design-export-docs-site"

// Result reports what a build did.
type Result struct {
	Warnings []string // token values dropped, README render problems
}

// Build writes the site for systems into out. Every system is built under out/<slug>/.
func Build(systems []*system.System, out string) (*Result, error) {
	if len(systems) == 0 {
		return nil, errors.New("no design systems given")
	}
	seen := map[string]bool{}
	for _, s := range systems {
		if !system.SafeRel(s.Slug) || strings.HasPrefix(s.Slug, "_") || strings.HasPrefix(s.Slug, ".") {
			return nil, fmt.Errorf("invalid system name %q", s.Slug)
		}
		if seen[s.Slug] {
			return nil, fmt.Errorf("two systems are named %q", s.Slug)
		}
		seen[s.Slug] = true
	}
	absOut, err := filepath.Abs(out)
	if err != nil {
		return nil, err
	}
	for _, s := range systems {
		if absOut == s.Dir || strings.HasPrefix(s.Dir, absOut+string(filepath.Separator)) {
			return nil, fmt.Errorf("output %s would overwrite the system in %s", out, s.Dir)
		}
	}
	if err := prepareOut(absOut); err != nil {
		return nil, err
	}

	res := &Result{}
	b := &builder{out: absOut, res: res, systems: systems}
	if err := b.writeViewerAssets(); err != nil {
		return nil, err
	}
	for _, s := range systems {
		if err := b.buildSystem(s); err != nil {
			return nil, fmt.Errorf("%s: %w", s.Slug, err)
		}
	}
	if err := b.render("index.html", "index.html", page{
		Title:   "Design systems",
		Content: b.siteIndex(),
	}); err != nil {
		return nil, err
	}
	return res, nil
}

func prepareOut(out string) error {
	entries, err := os.ReadDir(out)
	switch {
	case errors.Is(err, fs.ErrNotExist):
	case err != nil:
		return err
	case len(entries) > 0:
		if _, err := os.Stat(filepath.Join(out, marker)); err != nil {
			return fmt.Errorf("%s is not empty and was not created by design-export-docs; choose an empty or new folder", out)
		}
		for _, e := range entries {
			if err := os.RemoveAll(filepath.Join(out, e.Name())); err != nil {
				return err
			}
		}
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(out, marker), []byte("Generated by design-export-docs. Safe to delete.\n"), 0o644)
}

type builder struct {
	out     string
	res     *Result
	systems []*system.System
}

func (b *builder) writeViewerAssets() error {
	return fs.WalkDir(assets, "static", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		data, err := assets.ReadFile(p)
		if err != nil {
			return err
		}
		return b.write(path.Join("_viewer", path.Base(p)), data)
	})
}

func (b *builder) write(rel string, data []byte) error {
	p := filepath.Join(b.out, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, data, 0o644)
}

// copyTree copies the regular files under src into out/<dst>. Symlinks are refused: an export
// is untrusted and must not be able to pull in files from elsewhere on disk.
func (b *builder) copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if strings.HasPrefix(d.Name(), ".") && p != src {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&fs.ModeSymlink != 0 {
			return fmt.Errorf("refusing to copy symlink %s", p)
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		return b.write(path.Join(dst, filepath.ToSlash(rel)), data)
	})
}

func (b *builder) buildSystem(s *system.System) error {
	// Files copied as they are: fonts, assets and any other top-level folder of the export.
	top, err := os.ReadDir(s.Dir)
	if err != nil {
		return err
	}
	for _, e := range top {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") || e.Name() == "components" || e.Name() == "archived" {
			continue
		}
		if err := b.copyTree(filepath.Join(s.Dir, e.Name()), path.Join(s.Slug, e.Name())); err != nil {
			return err
		}
	}
	if _, err := os.Stat(filepath.Join(s.Dir, "components", "lib")); err == nil {
		if err := b.copyTree(filepath.Join(s.Dir, "components", "lib"), path.Join(s.Slug, "components", "lib")); err != nil {
			return err
		}
	}
	if err := b.copyFile(s, "tokens.json"); err != nil {
		return err
	}

	// tokens.css sits beside fonts/, so font urls stay relative.
	res := tokens.Compile(s.Tokens, tokens.Options{})
	for _, w := range res.Warnings {
		b.res.Warnings = append(b.res.Warnings, s.Slug+": tokens: "+w)
	}
	if err := b.write(path.Join(s.Slug, "tokens.css"), []byte(res.CSS)); err != nil {
		return err
	}

	// Stylesheet and bundle: claude.ai asset urls become paths. CSS resolves urls against the
	// stylesheet (components/), scripts against the page that loads them. Every consumer of
	// bundle.js is a preview at components/<Name>/, so its urls are relative to there.
	paths := s.BlobPaths()
	hasCSS, hasJS := false, false
	for _, f := range []struct {
		name, prefix string
		flag         *bool
	}{
		{"bundle.css", "../", &hasCSS},
		{"bundle.js", "../../", &hasJS},
	} {
		data, err := os.ReadFile(filepath.Join(s.Dir, "components", f.name))
		if errors.Is(err, fs.ErrNotExist) {
			continue
		} else if err != nil {
			return err
		}
		rw := rewrite.New(paths, f.prefix)
		if err := b.write(path.Join(s.Slug, "components", f.name), []byte(rw.Apply(string(data)))); err != nil {
			return err
		}
		if u := rw.Unresolved(); len(u) > 0 {
			return fmt.Errorf("components/%s refers to assets missing from the index: %s", f.name, strings.Join(u, ", "))
		}
		*f.flag = true
	}

	wrap := Wrap{TokensCSS: "../../tokens.css"}
	if len(s.Tokens.Themes) > 0 {
		wrap.Theme = strings.ToLower(s.Tokens.Themes[0].ID)
	} else {
		wrap.Theme = "light"
	}
	if hasCSS {
		wrap.BundleCSS = "../bundle.css"
	}
	for _, l := range s.Libraries { // l.File is components/lib/x.js; previews sit in components/<Name>/
		wrap.Libraries = append(wrap.Libraries, "../"+strings.TrimPrefix(l.File, "components/"))
	}
	if hasJS {
		wrap.Bundle = "../bundle.js"
	}

	view := newSystemView(s)
	for _, c := range s.Components {
		if !c.HasPreview {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(s.Dir, "components", c.Name, "preview.html"))
		if err != nil {
			return err
		}
		rw := rewrite.New(paths, "../../")
		html := WrapPreview(rw.Apply(string(raw)), wrap)
		if u := rw.Unresolved(); len(u) > 0 {
			return fmt.Errorf("components/%s/preview.html refers to assets missing from the index: %s", c.Name, strings.Join(u, ", "))
		}
		if err := b.write(path.Join(s.Slug, "components", c.Name, "preview.html"), []byte(html)); err != nil {
			return err
		}
	}
	return b.renderSystem(s, view)
}

func (b *builder) copyFile(s *system.System, name string) error {
	data, err := os.ReadFile(filepath.Join(s.Dir, name))
	if err != nil {
		return err
	}
	return b.write(path.Join(s.Slug, name), data)
}

// ---- page rendering ----

type page struct {
	Title    string
	Root     string // relative path to the site root, "" at the root, else "../" repeated
	SysRoot  string // relative path to the system folder
	System   *systemView
	Current  string // component being shown, for the sidebar
	Section  string // key of the page's section in the system nav
	ShowSide bool   // show the component sidebar
	Content  any
}

func (b *builder) render(templateFile, outPath string, p page) error {
	t, err := template.ParseFS(assets, "templates/layout.html", "templates/"+templateFile)
	if err != nil {
		return err
	}
	var buf strings.Builder
	if err := t.ExecuteTemplate(&buf, "layout", p); err != nil {
		return fmt.Errorf("%s: %w", templateFile, err)
	}
	return b.write(outPath, []byte(buf.String()))
}

func up(n int) string { return strings.Repeat("../", n) }

type systemView struct {
	Slug, Title, Namespace string
	Groups                 []groupView
	Components             int
	Previews               int
	HasCover               bool
	Themes                 int
	Pages                  []pageLink
}

// pageLink is an entry in a system's navigation. Path is relative to the system folder.
type pageLink struct{ Title, Path, Key string }

type groupView struct {
	Name  string
	Cards []cardView
}

type cardView struct {
	Name       string
	Subtitle   string
	Height     int
	HasPreview bool
	HasReadme  bool
	Current    bool
}

const ungrouped = "Other"

func newSystemView(s *system.System) *systemView {
	v := &systemView{Slug: s.Slug, Title: s.Title, Namespace: s.Namespace, Themes: len(s.Tokens.Themes)}
	v.Pages = navPages(s)
	byGroup := map[string][]cardView{}
	for _, c := range s.Components {
		if c.Name == "Cover" {
			v.HasCover = c.HasPreview
			continue
		}
		g := c.Card.Group
		if g == "" {
			g = ungrouped
		}
		h := c.Card.Height
		if h < 40 || h > 4000 {
			h = 120
		}
		byGroup[g] = append(byGroup[g], cardView{Name: c.Name, Subtitle: c.Card.Subtitle, Height: h,
			HasPreview: c.HasPreview, HasReadme: c.HasReadme})
		v.Components++
		if c.HasPreview {
			v.Previews++
		}
	}
	var names []string
	for g := range byGroup {
		names = append(names, g)
	}
	sort.Slice(names, func(i, j int) bool {
		if (names[i] == ungrouped) != (names[j] == ungrouped) {
			return names[j] == ungrouped
		}
		return strings.ToLower(names[i]) < strings.ToLower(names[j])
	})
	for _, g := range names {
		cards := byGroup[g]
		sort.Slice(cards, func(i, j int) bool { return strings.ToLower(cards[i].Name) < strings.ToLower(cards[j].Name) })
		v.Groups = append(v.Groups, groupView{Name: g, Cards: cards})
	}
	return v
}

type componentContent struct {
	Name       string
	Group      string
	Summary    string
	Height     int
	HasPreview bool
	Readme     template.HTML
	Props      string
}

type indexContent struct{ Systems []*systemView }

func (b *builder) siteIndex() indexContent {
	var ic indexContent
	for _, s := range b.systems {
		ic.Systems = append(ic.Systems, newSystemView(s))
	}
	return ic
}

var titleRe = regexp.MustCompile(`^\s*#\s+(.+?)\s*\n`)

// stripTitle drops a leading "# Name" heading: the page already has one.
func stripTitle(md, name string) string {
	if m := titleRe.FindStringSubmatch(md); m != nil && strings.EqualFold(strings.TrimSpace(m[1]), name) {
		return strings.TrimLeft(md[len(m[0]):], "\n")
	}
	return md
}

var inlineMD = strings.NewReplacer("`", "", "*", "", "_", " ")

// firstSentence is the opening sentence of the first prose paragraph, as plain text.
func firstSentence(md string) string {
	for _, para := range strings.Split(md, "\n\n") {
		para = strings.TrimSpace(para)
		if para == "" || strings.HasPrefix(para, "#") || strings.HasPrefix(para, "```") ||
			strings.HasPrefix(para, "|") || strings.HasPrefix(para, "<") {
			continue
		}
		para = strings.Join(strings.Fields(para), " ")
		if i := strings.Index(para, ". "); i >= 0 {
			para = para[:i+1]
		}
		para = strings.TrimSpace(inlineMD.Replace(para))
		if len(para) > 220 {
			para = para[:217] + "..."
		}
		return para
	}
	return ""
}

// props returns the component's type declarations: its own .d.ts, else its <Name>Props
// interface from index.d.ts. They are documentation, not type-checked.
func props(dir, name, indexTS string) string {
	if b, err := os.ReadFile(filepath.Join(dir, "components", name, name+".d.ts")); err == nil {
		return strings.TrimSpace(string(b))
	}
	return interfaceFrom(indexTS, name+"Props")
}

// interfaceFrom extracts "export interface <iface> ..." from TypeScript declarations, whether it
// is written over several lines or on one.
func interfaceFrom(src, iface string) string {
	q := regexp.QuoteMeta(iface)
	if m := regexp.MustCompile(`(?s)export interface ` + q + `\b[^{\n]*\{[ \t]*\n.*?\n\}`).FindString(src); m != "" {
		return m
	}
	return regexp.MustCompile(`export interface ` + q + `\b[^\n]*\}`).FindString(src)
}
